### ISSUE TITLE
i3blocks freezes with left and right click

### ISSUE THREAD

**Issue by gkluhana** [4khi1/i3blocks-airpods#2]
I am using the script for my bluetooth earphones which are not airpods. 
Using the middle click works fine and switches the audio profiles succesfully (what I was really only interested in)
However I have noticed that the statuses stop refreshing if I press left or right click on the audio block. 
The earphones do not disconnect or connect either.

**Comment by akhiljalagam** [comment]
yes, it freezes for a couple of seconds because connecting and disconnecting takes time.
you can add ```set -x``` to the script and see what's happening.
also don't forget to post here.

**Comment by gkluhana** [comment]
worked, thanks!
